### ISSUE TITLE
Implement custom form front-end for presence generator

### ISSUE THREAD

**Issue by neverything** [switchplus/components.underscores.me#2]
The generator currently allows the form to check against the several `types.json` file for the different base themes. As we will need more flexibility, read every component could be in any theme, we will have to implement a different approach.

Ideas are welcome.

- [ ] Build a proof-of-concept with per component checkboxes to be included in a theme
- [ ] Probably use a cron-job to get the latest components from the repo every hour or so

**Idea for a basic generator form:** The checkboxes in the form could be something like this

```yml
Header:
- Main Navigation above
- Meta and social navigation above
- Hero Unit with large background image
- Hero Unit with text
- Hero Unit with logo
- Navigation below
Content:
- Page with sidebar right
- Page with sidebar left
- Page with sidebar left and right
- Page full-width
- Blog with sidebar left
- Blog with sidebar right
- Blog with sidebar left and right
Footer:
- Meta and social navigation in footer
- Fat-Footer with widgets
- Copyright message
```

* These will need to be auto-generated from the components in the presence repo and we will need to have a way to search and replace them in `sass`, `php` and probably `js` files.
* Additionally the form elements might need to have some way to change the order of the included elements.

---

Related: #1
